/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface CarbonCreditMarketplaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "FEE_DENOMINATOR"
      | "FEE_NUMERATOR"
      | "addLiquidity"
      | "buyCredits"
      | "carbonCreditToken"
      | "creditReserve"
      | "getBuyQuote"
      | "getMarketplaceInfo"
      | "getSellQuote"
      | "getSpotPrice"
      | "owner"
      | "removeLiquidity"
      | "sellCredits"
      | "xrplReserve"
      | "xrplToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CreditsPurchased"
      | "CreditsSold"
      | "LiquidityAdded"
      | "LiquidityRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "FEE_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FEE_NUMERATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addLiquidity",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyCredits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "carbonCreditToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "creditReserve",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBuyQuote",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketplaceInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSellQuote",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSpotPrice",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeLiquidity",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sellCredits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "xrplReserve",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "xrplToken", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "FEE_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FEE_NUMERATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buyCredits", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "carbonCreditToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creditReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBuyQuote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketplaceInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSellQuote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSpotPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sellCredits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xrplReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "xrplToken", data: BytesLike): Result;
}

export namespace CreditsPurchasedEvent {
  export type InputTuple = [
    buyer: AddressLike,
    creditAmount: BigNumberish,
    xrplPaid: BigNumberish
  ];
  export type OutputTuple = [
    buyer: string,
    creditAmount: bigint,
    xrplPaid: bigint
  ];
  export interface OutputObject {
    buyer: string;
    creditAmount: bigint;
    xrplPaid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreditsSoldEvent {
  export type InputTuple = [
    seller: AddressLike,
    creditAmount: BigNumberish,
    xrplReceived: BigNumberish
  ];
  export type OutputTuple = [
    seller: string,
    creditAmount: bigint,
    xrplReceived: bigint
  ];
  export interface OutputObject {
    seller: string;
    creditAmount: bigint;
    xrplReceived: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityAddedEvent {
  export type InputTuple = [
    provider: AddressLike,
    creditAmount: BigNumberish,
    xrplAmount: BigNumberish
  ];
  export type OutputTuple = [
    provider: string,
    creditAmount: bigint,
    xrplAmount: bigint
  ];
  export interface OutputObject {
    provider: string;
    creditAmount: bigint;
    xrplAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityRemovedEvent {
  export type InputTuple = [
    provider: AddressLike,
    creditAmount: BigNumberish,
    xrplAmount: BigNumberish
  ];
  export type OutputTuple = [
    provider: string,
    creditAmount: bigint,
    xrplAmount: bigint
  ];
  export interface OutputObject {
    provider: string;
    creditAmount: bigint;
    xrplAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CarbonCreditMarketplace extends BaseContract {
  connect(runner?: ContractRunner | null): CarbonCreditMarketplace;
  waitForDeployment(): Promise<this>;

  interface: CarbonCreditMarketplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  FEE_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  FEE_NUMERATOR: TypedContractMethod<[], [bigint], "view">;

  addLiquidity: TypedContractMethod<
    [creditAmount: BigNumberish, xrplAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  buyCredits: TypedContractMethod<
    [creditAmountOut: BigNumberish],
    [void],
    "nonpayable"
  >;

  carbonCreditToken: TypedContractMethod<[], [string], "view">;

  creditReserve: TypedContractMethod<[], [bigint], "view">;

  getBuyQuote: TypedContractMethod<
    [creditAmountOut: BigNumberish],
    [bigint],
    "view"
  >;

  getMarketplaceInfo: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        _creditReserve: bigint;
        _xrplReserve: bigint;
        spotPrice: bigint;
      }
    ],
    "view"
  >;

  getSellQuote: TypedContractMethod<
    [creditAmountIn: BigNumberish],
    [bigint],
    "view"
  >;

  getSpotPrice: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  removeLiquidity: TypedContractMethod<
    [creditAmount: BigNumberish, xrplAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  sellCredits: TypedContractMethod<
    [creditAmountIn: BigNumberish],
    [void],
    "nonpayable"
  >;

  xrplReserve: TypedContractMethod<[], [bigint], "view">;

  xrplToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "FEE_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FEE_NUMERATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addLiquidity"
  ): TypedContractMethod<
    [creditAmount: BigNumberish, xrplAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "buyCredits"
  ): TypedContractMethod<[creditAmountOut: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "carbonCreditToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "creditReserve"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBuyQuote"
  ): TypedContractMethod<[creditAmountOut: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMarketplaceInfo"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        _creditReserve: bigint;
        _xrplReserve: bigint;
        spotPrice: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSellQuote"
  ): TypedContractMethod<[creditAmountIn: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSpotPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeLiquidity"
  ): TypedContractMethod<
    [creditAmount: BigNumberish, xrplAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sellCredits"
  ): TypedContractMethod<[creditAmountIn: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "xrplReserve"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "xrplToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "CreditsPurchased"
  ): TypedContractEvent<
    CreditsPurchasedEvent.InputTuple,
    CreditsPurchasedEvent.OutputTuple,
    CreditsPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "CreditsSold"
  ): TypedContractEvent<
    CreditsSoldEvent.InputTuple,
    CreditsSoldEvent.OutputTuple,
    CreditsSoldEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityAdded"
  ): TypedContractEvent<
    LiquidityAddedEvent.InputTuple,
    LiquidityAddedEvent.OutputTuple,
    LiquidityAddedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityRemoved"
  ): TypedContractEvent<
    LiquidityRemovedEvent.InputTuple,
    LiquidityRemovedEvent.OutputTuple,
    LiquidityRemovedEvent.OutputObject
  >;

  filters: {
    "CreditsPurchased(address,uint256,uint256)": TypedContractEvent<
      CreditsPurchasedEvent.InputTuple,
      CreditsPurchasedEvent.OutputTuple,
      CreditsPurchasedEvent.OutputObject
    >;
    CreditsPurchased: TypedContractEvent<
      CreditsPurchasedEvent.InputTuple,
      CreditsPurchasedEvent.OutputTuple,
      CreditsPurchasedEvent.OutputObject
    >;

    "CreditsSold(address,uint256,uint256)": TypedContractEvent<
      CreditsSoldEvent.InputTuple,
      CreditsSoldEvent.OutputTuple,
      CreditsSoldEvent.OutputObject
    >;
    CreditsSold: TypedContractEvent<
      CreditsSoldEvent.InputTuple,
      CreditsSoldEvent.OutputTuple,
      CreditsSoldEvent.OutputObject
    >;

    "LiquidityAdded(address,uint256,uint256)": TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;
    LiquidityAdded: TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;

    "LiquidityRemoved(address,uint256,uint256)": TypedContractEvent<
      LiquidityRemovedEvent.InputTuple,
      LiquidityRemovedEvent.OutputTuple,
      LiquidityRemovedEvent.OutputObject
    >;
    LiquidityRemoved: TypedContractEvent<
      LiquidityRemovedEvent.InputTuple,
      LiquidityRemovedEvent.OutputTuple,
      LiquidityRemovedEvent.OutputObject
    >;
  };
}
