/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface CarbonCreditMarketplaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "buyCredits"
      | "buyPrice"
      | "carbonCreditToken"
      | "getMarketplaceInfo"
      | "owner"
      | "sellCredits"
      | "sellPrice"
      | "setBuyPrice"
      | "setSellPrice"
      | "withdrawCredits"
      | "withdrawXrpl"
      | "xrplToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CreditsPurchased" | "CreditsSold" | "PriceUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "buyCredits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "buyPrice", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "carbonCreditToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketplaceInfo",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "sellCredits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "sellPrice", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setBuyPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSellPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawCredits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawXrpl",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "xrplToken", values?: undefined): string;

  decodeFunctionResult(functionFragment: "buyCredits", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buyPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "carbonCreditToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketplaceInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sellCredits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sellPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setBuyPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSellPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawCredits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawXrpl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "xrplToken", data: BytesLike): Result;
}

export namespace CreditsPurchasedEvent {
  export type InputTuple = [
    buyer: AddressLike,
    amount: BigNumberish,
    totalCost: BigNumberish
  ];
  export type OutputTuple = [buyer: string, amount: bigint, totalCost: bigint];
  export interface OutputObject {
    buyer: string;
    amount: bigint;
    totalCost: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreditsSoldEvent {
  export type InputTuple = [
    seller: AddressLike,
    amount: BigNumberish,
    totalPayout: BigNumberish
  ];
  export type OutputTuple = [
    seller: string,
    amount: bigint,
    totalPayout: bigint
  ];
  export interface OutputObject {
    seller: string;
    amount: bigint;
    totalPayout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceUpdatedEvent {
  export type InputTuple = [
    newBuyPrice: BigNumberish,
    newSellPrice: BigNumberish
  ];
  export type OutputTuple = [newBuyPrice: bigint, newSellPrice: bigint];
  export interface OutputObject {
    newBuyPrice: bigint;
    newSellPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CarbonCreditMarketplace extends BaseContract {
  connect(runner?: ContractRunner | null): CarbonCreditMarketplace;
  waitForDeployment(): Promise<this>;

  interface: CarbonCreditMarketplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buyCredits: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  buyPrice: TypedContractMethod<[], [bigint], "view">;

  carbonCreditToken: TypedContractMethod<[], [string], "view">;

  getMarketplaceInfo: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        creditBalance: bigint;
        xrplBalance: bigint;
        currentBuyPrice: bigint;
        currentSellPrice: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  sellCredits: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  sellPrice: TypedContractMethod<[], [bigint], "view">;

  setBuyPrice: TypedContractMethod<
    [newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  setSellPrice: TypedContractMethod<
    [newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawCredits: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawXrpl: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  xrplToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buyCredits"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "buyPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "carbonCreditToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getMarketplaceInfo"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        creditBalance: bigint;
        xrplBalance: bigint;
        currentBuyPrice: bigint;
        currentSellPrice: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "sellCredits"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sellPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setBuyPrice"
  ): TypedContractMethod<[newPrice: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSellPrice"
  ): TypedContractMethod<[newPrice: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawCredits"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawXrpl"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "xrplToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "CreditsPurchased"
  ): TypedContractEvent<
    CreditsPurchasedEvent.InputTuple,
    CreditsPurchasedEvent.OutputTuple,
    CreditsPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "CreditsSold"
  ): TypedContractEvent<
    CreditsSoldEvent.InputTuple,
    CreditsSoldEvent.OutputTuple,
    CreditsSoldEvent.OutputObject
  >;
  getEvent(
    key: "PriceUpdated"
  ): TypedContractEvent<
    PriceUpdatedEvent.InputTuple,
    PriceUpdatedEvent.OutputTuple,
    PriceUpdatedEvent.OutputObject
  >;

  filters: {
    "CreditsPurchased(address,uint256,uint256)": TypedContractEvent<
      CreditsPurchasedEvent.InputTuple,
      CreditsPurchasedEvent.OutputTuple,
      CreditsPurchasedEvent.OutputObject
    >;
    CreditsPurchased: TypedContractEvent<
      CreditsPurchasedEvent.InputTuple,
      CreditsPurchasedEvent.OutputTuple,
      CreditsPurchasedEvent.OutputObject
    >;

    "CreditsSold(address,uint256,uint256)": TypedContractEvent<
      CreditsSoldEvent.InputTuple,
      CreditsSoldEvent.OutputTuple,
      CreditsSoldEvent.OutputObject
    >;
    CreditsSold: TypedContractEvent<
      CreditsSoldEvent.InputTuple,
      CreditsSoldEvent.OutputTuple,
      CreditsSoldEvent.OutputObject
    >;

    "PriceUpdated(uint256,uint256)": TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;
    PriceUpdated: TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;
  };
}
